version: '2'
services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.ii.org.nz
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.ii.org.nz'
        #gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['omniauth_providers'] = [
            { name: 'github', app_id: '46bed3af9ef46d052c1f',  app_secret: '6f2a76f7a5bf9b45a6bc98e722cd6ea7cdfd03de', args: { scope: 'user:email' } },
            { name: 'twitter', app_id: 'AmoyCLmkqT1PmDAMZttqiDX2A',  app_secret: 'Z3QU5WFgmjYctMSoYfqgnAnw79CsKRmdRhryevCG4NkJC6NaQM' }
          ]
        gitlab_rails['omniauth_enabled'] = true
        gitlab_rails['omniauth_allow_single_sign_on'] = ['twitter','github','google_oauth2']
        gitlab_rails['omniauth_block_auto_created_users'] = true
        # more gitlab.rb conf, each on own line
      VIRTUAL_HOST: gitlab.ii.org.nz
    ports: # you'll need to run your hosts ssh on another port
      # - "2222:22"
      - "22:22"
    volumes:
      # This directory must have cert files
      - ./volumes/gitlab/config:/etc/gitlab
      - ./volumes/gitlab/logs:/var/log/gitlab
      - ./volumes/gitlab/data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro
      
  jenkins:
    image: jenkinsci/jenkins:latest
    hostname: jenkins.ii.org.nz
    restart: always
    ports: # for JNLP (Web Start) slave adding
      - "50000:50000"
    volumes:
      # This directory must have cert files
      - ./volumes/jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: jenkins.ii.org.nz
      VIRTUAL_PORT: 8080
      JAVA_OPTS: -Dhudson.footerURL=http://ii.org.nz
      
  mattermost_db:
    image: mattermost/mattermost-prod-db
    volumes:
      - ./volumes/mattermost/postgresql_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  mattermost_app:
    image: mattermost/mattermost-prod-app
    links:
      - mattermost_db:db
    volumes:
      - ./volumes/mattermost/app_config:/mattermost/config:rw
      - ./volumes/mattermost/app_data:/mattermost/data:rw
      - /etc/localtime:/etc/localtime:ro

  mattermost_web:
    image: mattermost/mattermost-prod-web
    links:
      - mattermost_app:app
    volumes:
      # This directory must have cert files
      - ./volumes/mattermost/web_cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=mattermost.ii.org.nz
      - MATTERMOST_ENABLE_SSL=false
      - PLATFORM_PORT_80_TCP_PORT=80

